### ISSUE TITLE
Not issue but request

### ISSUE THREAD

**Issue by lauccode** [xulion/scope4code#16]
Hello,
I looked for this plugin because I used cscope with vim a lot.
I'm happy to find this plugin under vs code.

Maybe I don't use vs code very well.
But when I try to select a result I can only do with 'ctrl' + mouse'
Would it be possible to add the possibility to select the search result of this plugin with the keyboard ?
Arrow key for exemple + 'enter' ?

Regards

**Comment by xulion** [comment]
Sure, good suggestion. Give me few weeks (it's my spare time project anyway :-) ), will try investigate make some update in Mar.

**Comment by xulion** [comment]
@lauccode, Just realized that the VS code has the functionality already so what you need to do is to setup a key binding. 

Goto menu, file->preferences->keyboard shotcuts. in the new window search for "Open link", then you can set whatever you want to open the link. I tried ctrl+right and it works well.

Pls let me know if this works for you and I will close this issue. 

Thanks!

**Comment by lauccode** [comment]
Perfect !
It is working well
You can close the issue
Thanks
