### ISSUE TITLE
please support windows for vscode

### ISSUE THREAD

**Issue by bujxu** [xulion/scope4code#17]
when i use cscope at windows(cscope for windows), but when i use the command: build database
vscode show me that command 'extension.build' not found

i don't know what's going on until i found that  It might not work in Windows.

**Comment by xulion** [comment]
I never tested in windows yet. To let the extension work, 'cscope' has to be accessiable from commandline globally. Do you have cscope installed for windows and have PATH configured?

**Comment by xulion** [comment]
@bujxu 
I recently tested in windows, it works when you have scope installed. I've added link for downloading cscope for windows in extension documentation. I'm now closing this issue. If you have any issues, pls let me know or submit a new one.

Thanks!
