### ISSUE TITLE
cscope is pre-built

### ISSUE THREAD

**Issue by Piping** [xulion/scope4code#21]
Hi, 

my cscope database is prebuilt under project root, but the tool said there is not database, can you help? 

Thx

**Comment by xulion** [comment]
Hi,

The extension assumes the database is in .vscode/cscope folder under currect workspace. If you use F1 and select build database, then it will create the folder and then build result under it. If you want to use your prebuild database, then you can try create the cscope folder and copy database into it. 

Let me know if this works.

Thanks!

**Comment by xulion** [comment]
Now the plug in does not supports specifying path for existing database. One workaround you migth try is to create a symbolic link inside the folder.  

And I will change this issue to enhancement and next build I would try to make it configurable.
