### ISSUE TITLE
[Bug] No 'cscope_conf.json' is created when enabling scope4code

### ISSUE THREAD

**Issue by pidgeon777** [xulion/scope4code#49]
The extension readme states that configuration is supported via cscope_conf.json. This file will be automatically creted in .vscode folder once the extension is enabled.

This unfortunately doesn't happen in my setup.

Windows 10 Professional x64
Visual Studio Code 1.42.0

**Comment by xulion** [comment]
Ahh, yes. Recent updates I removed this as I'm trying to move all settings to vscode preference. Config file in workspace folder is not recommended for vscode extension. Now the tool would use default setting if there is no config json file. You can manually create json file with content below. The tool will detect the file and apply settings in it. Eventually I will allow set path in vscode preference.
```
{
    "version": "0.0.5",
    "open_new_column" : "no",
    "engine_configurations": [
        {
            "cscope" : {
                "paths" : [
                    "${workspaceRoot}/"
                ]
            }
        }
    ]
}
```

**Comment by xulion** [comment]
cscope_conf.json is obsoleted. All configurations are in setting now
