### ISSUE TITLE
scope4code doesn't work after git checkout another branch

### ISSUE THREAD

**Issue by Minjian** [xulion/scope4code#52]
Hi,

Thank you so much for creating this scope4code for VS code! I really like this tool and it is way more faster than using the default C/C++ IntelliSense when finding all references (I already disable IntelliSense ;-) ).

However, during my regular workflow, sometimes I need to "git checkout" to different branches. I found scope4code doesn't work after I "git checkout" to another branch. It just shows nothing after I click the "find all references" or other cscope search commands. Even I try to rebuild the database, an error like the following will show up.
`/Users/mjliu/githubs/dual-pan/super/platform/micrium_os/tests/usb/host/class-test-suite/RAM cscope: cannot find file Calc/Host cscope: cannot find file App/app_usbh_ram_calc.h cscope: cannot find file /Users/mjliu/githubs/dual-pan/super/platform/micrium_os/tests/usb/host/class-test-suite/RAM cscope: cannot find file Calc/Host cscope: cannot find file App/app_usbh_ram_calc.c cscope: cannot find file /Users/mjliu/githubs/dual-pan/super/platform/micrium_os/tests/usb/host/class-test-suite/CDC cscope: cannot find file ACM/Host-App/app_usbh_acm.h cscope: cannot find file /Users/mjliu/githubs/dual-pan/super/platform/micrium_os/tests/usb/host/class-test-suite/CDC cscope: cannot find file ACM/Host-App/app_usbh_acm.c cscope: cannot find file /Users/mjliu/githubs/dual-pan/super/tool/gcovr/gcovr/tests/wspace/src cscope: cannot find file code/main.cpp cscope: cannot rename file ncscope.in.out to file cscope.in.out`

I added the .vscode/cscope folder to the .gitignore file so I can make sure related cscope files are still there after I switch to another branch. 

The workaround I discover is to delete all cscope related files (delete the .vscode/cscope folder), then build the database again.

Does anyone have such an issue?

Best regards,
MJ

**Comment by Minjian** [comment]
Just realize it is able to solve the issue by adding the "-d" option to avoid update cross-reference.
```
    "scope4code.engineCommands": {
        "config": [
            {
                "find_all_ref": "cscope -d -q -k -L0 ${text}",
                "find_define": "cscope -d -q -k -L1 ${text}",
                "find_callee": "cscope -d -q -k -L2 ${text}",
                "find_caller": "cscope -d -q -k -L3 ${text}",
                "find_text": "cscope -d -q -k -L4 ${text}",
            }
        ]
    },
```
I guess my project is pretty large, so it will take a while to update the cross-reference after switch to another branch.

**Comment by xulion** [comment]
The idea is to use customized configure to define all commands. I want to make the setting generic so in the future it could be any engine like ctag.
