### ISSUE TITLE
Selecting an already build database

### ISSUE THREAD

**Issue by JayroALH** [xulion/scope4code#54]
Hi, i work with some big linux apps and a cscope database is created with each build,

There is a way to manually select a database file instead of having to build one from scratch?

**Comment by xulion** [comment]
Thanks for using the extension. I've been quite a slacker recently. To do so you can edit the configure file (if it does not exist then create one):
```
 .vscode/cscope_conf.json
{
    "version": "0.0.13",
    "open_new_column" : "no",
    "engine_configurations": [
        {
            "cscope" : {
                "paths" : [
                    "${workspaceRoot}"
                ],
]                "database_path" : "${workspaceRoot}/.vscode/cscope"
            }
        }
    ]
}
```

what you need to do is to update database_path attribute.

I'm trying to find time refactor the configuration (move to vs code preference) and I try to avoid user to edit the json file directly. For now you shall use the JSON file. My next update might require you to update the path again in vscode preference.

**Comment by JayroALH** [comment]
Thanks for the info
